#!/usr/bin/perl

print "Please enter your radius:";
chomp($radius = <STDIN>);
$pi = 3.141592654;


if ($radius < 0)
{
	$circ = 0;
}
else{
	$circ = 2 * $pi * $radius;
}
print "The circumference of a circle of radius $radius  is $circ .\n";
