#!/usr/bin/perl
use 5.010;
greet("Peter");
greet("Marry");

sub greet{
	state $last_one;
	$name = shift @_;
	print "Hi! $name.";
	if(defined $last_one){
		print "$last_one is also here!\n";
	}
	else{
		print "you are the first!\n";
	}
	$last_one = $name;
}

